language: ruby
cache:
  directories:
    - /home/travis/.rvm/
rvm:
 - 2.5.1
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - echo "$MASTER_KEY" > config/master.key
