# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  #username: reservation
  #password:
  #host: localhost
  #port: 5432
  #min_messages: notice
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reservation

test:
  <<: *default
  database: reservation_test

production:
  <<: *default
  database: reservation_production
  username: reservation
  password: <%= ENV['MOH_DATABASE_PASSWORD'] %>
